### ISSUE TITLE
accessing request in get_queryset

### ISSUE THREAD

**Issue by ayushin** [encode/django-vanilla-views#123]
it would be great if request object was accessible in get_queryset()

would it be an option to save request in get() to self.request before calling get_queryset?

**Comment by adamchainz** [comment]
I believe it already available as `self.request`, because Django’s `View` class does so here:

https://github.com/django/django/blob/e361621dbc77b5d926ec4deff5e7c792a61db71e/django/views/generic/base.py#L89

Can you check that?

**Comment by ayushin** [comment]
sorry had a long day

**Comment by ayushin** [comment]
sorry had a long day
