### ISSUE TITLE
project [not] abandoned

### ISSUE THREAD

**Issue by rafalkrupinski** [encode/django-vanilla-views#128]
Hi,
I'm new to django and I'm just exploring available extensions.

I see this project has last commit two years ago and it seems abandoned. I wanted to ask, is the project complete and free of any bugs, or the idea behind the project proven wrong and been abandoned, or proven good and been incorporated in django or does it have a successor?

**Comment by carltongibson** [comment]
It's in perfect working order. No changes needed.

**Comment by adamchainz** [comment]
Yes, it works fine and shouldn't have any incompatibilities with Python/Django versions, at least none have been reported.

I would be maintain the metadata, build process, and tests through [my automated process](https://adamj.eu/tech/2020/04/02/maintaining-multiple-python-projects-with-myrepos/), if @tomchristie would assist in making me a collaborator, per https://github.com/encode/django-vanilla-views/issues/72#issuecomment-655595288 . But I don't think it's worth any other collaborators diving in to try those things unless something actively breaks.

**Comment by lovelydinosaur** [comment]
@adamchainz What do you need friend... slice of the PyPi action?
Or do I need to save you from making more work for yourself?
